### ISSUE TITLE
Ubuntu 22.04 (1.0.0) benchmark released

### ISSUE THREAD

**Issue by modem7** [ansible-lockdown/UBUNTU22-CIS#10]
Heya,

Thank you very much for your work!

Just an FYI in case you weren't aware, it looks like the 22.04 benchmark has been [released](https://www.cisecurity.org/benchmark/ubuntu_linux) (1.0.0), unsure if anything needs updating.

Thanks again!

**Comment by uk-bolly** [comment]
hi @modem7 

This is now no live in the devel branch. with the initial 1.0.0 release and accompanying audit repository.

Best regards

uk-bolly

**Comment by modem7** [comment]
Thank you!
