### ISSUE TITLE
rsyslog service not working after applying playbook

### ISSUE THREAD

**Issue by bnicolae86** [ansible-lockdown/UBUNTU22-CIS#102]
**Describe the Issue**
rsyslog service is not working after applying the playbook, rsyslog.conf seems messed up.

**Expected Behavior**
rsyslog service up & running 

**Actual Behavior**
rsyslog service not starting

**Environment (please complete the following information):**

- branch being used: Ubuntu22-cis_v1.0.0
- Ansible Version: 2.15.4

**Possible Solution**
replace config with default one

**Comment by uk-bolly** [comment]
hi @bnicolae86 

Thank you for taking the time to raise this issue. Is it possible you could test this with one of the newer branches. We are about to release a new update and this feedback would be excellent. I have tested this on the current main branch and the devel branch and all appears to be working on a clean build system.

many thanks

uk-bolly

**Comment by bnicolae86** [comment]
Using tag 1.1.0 solved the issue. I was using an old tag.
