### ISSUE TITLE
wrong configuration of umask parameter

### ISSUE THREAD

**Issue by bnicolae86** [ansible-lockdown/UBUNTU22-CIS#103]
**Describe the Issue**
wrong `umask` parameter set in `/etc/login.defs`, the console is showing error: 
**`configuration error - unknown item 'umask' (notify administrator)`**

**Expected Behavior**
set `UMASK` parameter in `/etc/login.defs`

**Actual Behavior**
`umask` param set instead of `UMASK` (case sensitive), 

**Possible Solution**
remove `umask` line and apply proper `UMASK` parameter

**Comment by uk-bolly** [comment]
hi @bnicolae86 

Thank you for raising this issue, Just following up on this please can you confirm the branch you are using and if you have downloaded the latest version?
I am not able to reproduce this issue in either the devel or main branches.

Many thanks

uk-bolly

**Comment by bnicolae86** [comment]
I'm using release 1.0.0 because appears to be the latest. But there is a new tag 1.1.0 and using this is working fine. Thanks.
