### ISSUE TITLE
1.1.2.2, 1.1.2.3, 1.1.2.4 conditional statement uses also 1.1.2.1 var

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/UBUNTU22-CIS#105]
**Question**
Is there a good reason for having an Ansible conditional which uses  [`rule_1.1.2.1`'s variable](https://code.siemens.com/infosec-pss-gov/security-crafter-baseline-automations/ansible-lockdown/ubuntu22-cis/-/blob/devel/tasks/section_1/cis_1.1.2.x.yml#L45) for rules **1.1.2.2, 1.1.2.3, 1.1.2.4** ?  :
```yaml
  when:
      - ubtu22cis_rule_1_1_2_1 or                                                    # Purpose of this ?
        ubtu22cis_rule_1_1_2_2 or
        ubtu22cis_rule_1_1_2_3 or
        ubtu22cis_rule_1_1_2_4
```

I imagined that this would ensure the **1.1.2.2, 1.1.2.3, 1.1.2.4 task-block** will never be executed **if rule `1.1.2.1` is inactive**, respectively when: `ubtu22cis_rule_1_1_2_1` is set to `false`, but  I did not detect in the role other similar approaches. 

Was this the initial idea behind it or it's just a super-small inaccuracy related to variables in conditionals?

**Environment (please complete the following information):**
N/A

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This is a great catch, the first conditional was based on a other baselines where it was classified as level2.
This is not the case on this and you PR is spot on.

Thank you

uk-bolly
