### ISSUE TITLE
Rule 2.2.2 has wrong conditional

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/UBUNTU22-CIS#108]
**Describe the Issue**
Rule "2.2.2 | PATCH | Ensure Avahi Server is not installed" has a wrong conditional:
```
  when:
      - "'avahi' in ansible_facts.packages"
```

**Expected Behavior**
When avahi is installed, this rule should uninstall it.

**Actual Behavior**
This never gets executed, as the package name is slightly different: NOT `avahi`, but `avahi-daemon`

**Control(s) Affected**
2.2.2

**Environment (please complete the following information):**

- branch being used: [e.g. devel]

**Additional Notes**
To quickly see, in an interactive manner(quickly filter/sort), what's inside the `ansible_facts.packages`, you can try this small python snippet:
```
import apt
cache = apt.Cache()

for mypkg in cache:
    if cache[mypkg.name].is_installed:
        print mypkg.name
````
which would have as stdout:
```
audispd-plugins
auditd
avahi-daemon    ***** `avahi` will NOT be in package.facts, rule will be skipped
awscli
base-files
```

**Possible Solution**
I'll provide a PR.

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

That is a brilliant catch, thank you for the PR. This has now been merged.

regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This issue was merged to devel a couple of weeks ago.
I will close this Issue, if this does not resolve your issue please reopen.

Many thanks as always

uk-bolly
