### ISSUE TITLE
Wrong path in control 1.8.3

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#114]
**Describe the Issue**

The role has both

~~~
     path: /etc/gdm3/greeter.dconf-defaults
~~~

and
~~~
     path: /etc/gdm3/greeter.dconf-default
~~~

for Controls 1.8.2 and 1.8.3, respectively.

The latter is not correct and should be changed to also read `defaults`.

**Expected Behavior**
n/a

**Actual Behavior**
n/a

**Control(s) Affected**
- 1.8.2
- 1.8.3

**Environment (please complete the following information):**

- branch being used: devel

**Additional Notes**
Anything additional goes here

**Possible Solution**
see above.

**Comment by uk-bolly** [comment]
hi @bgro 

This issue was merged to devel a couple of weeks ago.
I will close this Issue, if this does not resolve your issue please reopen.

Many thanks as always

uk-bolly
