### ISSUE TITLE
Wrong value in `defaults/main.yml` file for `ubtu22cis_grub_file` variable

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/UBUNTU22-CIS#115]
**Describe the Issue**
In my opinion, after analyzing why CIS reports a failure for rule  `1.4.2 Ensure permissions on bootloader config are configured`, the [current value set](https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/8713b3fc8f39e86cab5f015c30d9977461ba07e8/defaults/main.yml#L576) in `defaults/main.yml` file for variable `ubtu22cis_grub_file`  is wrong. 

I think it may ended up with this value, as [this is a mix](https://help.ubuntu.com/community/Grub2/Setup#The_Menu:_.2Fboot.2Fgrub.2Fgrub.cfg) between:
          - **DEFAULT FILE**: `/etc/default/grub`
          - **THE AUTO-GENERATED GRUB FILE**: `/boot/grub/grub.cfg`

**Expected Behavior**
`ubtu22cis_grub_file: /etc/grub/grub.cfg` -> CIS reports rule 1.4.2 as passed

**Actual Behavior**
`ubtu22cis_grub_file: /etc/default/grub.cfg` -> CIS reports rule 1.4.2 as failed

**Control(s) Affected**
1.4.2

**Environment (please complete the following information):**

- branch being used: devel

**Possible Solution**
I'll add a PR.

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This issue was merged to devel a couple of weeks ago.
I will close this Issue, if this does not resolve your issue please reopen.

Many thanks as always

uk-bolly
