### ISSUE TITLE
1.8.4 rule: extra gdm3 question

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/UBUNTU22-CIS#126]
**Question**
While analyzing issue #124, I was wondering if, for rule **1.8.4**:
[`path: /etc/dconf/profile/session`](https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/a902c1dc0b13b4d8462b662bbacc4102cf523589/tasks/section_1/cis_1.8.x.yml#L71) shouldn't be replaced by `/etc/dconf/profile/{{ ubtu22cis_dconf_db_name }}` ?

Is there a special purpose for this hardcoded value: `session` ?
A lot of docs(e.g. [this@Tenable](https://www.tenable.com/audits/items/CIS_Red_Hat_EL7_STIG_v2.0.0_L1_Server.audit:4ff929aab05321df7ca4df1e5d68455b)) mention `/etc/dconf/profile/local`, `local` being the default value for `{{ ubtu22cis_dconf_db_name }}`, that's why I wanted to double-check with you if I misunderstood this rule.

**Environment (please complete the following information):**
N/A

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

Great catch on this the rule has been taken too literally. I have amended accordingly.

many thanks

uk-bolly
