### ISSUE TITLE
Wrong rule text for rule 1.8.6

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#14]
**Describe the Issue**
The rule text given in the title of the tasks concerned with R1.8.6 is wrong.

It is `Ensure GDM screen locks when the user is idle` but
it should be `Ensure GDM automatic mounting of removable media is disabled`

**Expected Behavior**
n/a
**Actual Behavior**
n/a
**Control(s) Affected**
R1.8.6

**Environment (please complete the following information):**
n/a

**Additional Notes**
n/a

**Possible Solution**
Enter the correct rule text.

**Comment by MrSteve81** [comment]
This was added to PR [#22] and is now in devel feel free to test out and let us know.
