### ISSUE TITLE
3.1.1 Incorrect profile tags

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#140]
**Describe the Issue**
Incorrect profile tags for the control. The CIS hardening manual states that this control is applicable for Level 1 Server and Workstation.
```
- name: "3.1.1 | PATCH | Ensure system is checked to determine if IPv6 is enabled"
...
  tags:
      - level2-server
      - level2-workstation
```

**Expected Behavior**
This role should run on level 1 server and workstation as well.

**Actual Behavior**
It is skipped when running as level 1 profile

**Control(s) Affected**
3.1.1

**Possible Solution**
Adjust tags to be level1

**Comment by uk-bolly** [comment]
hi @zac90 

good catch. updated

thanks

uk-bolly
