### ISSUE TITLE
Control 1.1.10 usb_storage blacklisting requires initramfs update

### ISSUE THREAD

**Issue by paulquevedojdrf** [ansible-lockdown/UBUNTU22-CIS#144]
**Question**

Not sure if its just my machine, but blacklisting the usb_storage module doesn't persist across power cycles unless I update the boot image (`sudo update-initramfs -u`). 
Is this something that's required to be done outside this playbook?

**Environment (please complete the following information):**

- Ansible Version: 2.13.13
- Host Python Version: 3.10
- Ansible Server Python Version: 3.8
- Additional Details:

**Comment by uk-bolly** [comment]
hi @paulquevedojdrf 

Thanks for raising this question. This should indeed and appears to work for me if it runs all the 1.1.10 controls. Can i ask how you are testing it? to be able to load it again?

many thanks

uk-bolly

**Comment by paulquevedojdrf** [comment]
Fresh install of 22.04.3 onto a physical machine
upgrade, reboot. 
`ansible-playbook site.yml --tags rule_1.1.10` 
plug in a USB storage device
reboot
After logging in the device is automounted in gnome. 

run `sudo update-initramfs -u`
reboot
Device is no longer automounted in gnome on subsequent reboots

**Comment by uk-bolly** [comment]
hi @paulquevedojdrf 

Thank you for taking the time to raise the question and subsequent fix. I am adding this fix into an upcoming release, which i hope to get out over the next week.

thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @paulquevedojdrf 

I believe that this issue has been addressed and the fix merged?
I will close this issue, please feel free to reopen or raise a new one if this particular problem still exists.

Many thanks

uk-bolly
