### ISSUE TITLE
Serveral rules appear in different tasks with different rule texts

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#15]
**Describe the Issue**

- Rule 1.1.2.3 listed with two different titles, namely 'Ensure noexec option set on /tmp partition ' and 'Ensure nosuid option set on /tmp partition
- Rule 1.1.2.4 listed with two different titles, namely 'Ensure nosuid option set on /tmp partition ' and 'Ensure noexec option ntp'                                                                                                                                                     
- Rule 2.1.4.3 listed with two different titles, namely 'Ensure ntp is enabled and running' and 'Ensure ntp is running as user ntp

**Expected Behavior**
Rule titles should be consistent

**Actual Behavior**
Rule titles are not consistent

**Control(s) Affected**
1.1.2.3, 1.1.2.4 and 2.1.4.3

**Environment (please complete the following information):**
n/a

**Additional Notes**
n/a

**Possible Solution**
Adjust the rule titles according to the CIS source.

**Comment by MrSteve81** [comment]
This was added to PR [#22] and is now in devel feel free to test out and let us know.
