### ISSUE TITLE
Release latest 1.2.0 to Ansible Galaxy?

### ISSUE THREAD

**Issue by colinbruner** [ansible-lockdown/UBUNTU22-CIS#156]
**Question**
Hi, would it be possible to release the latest 1.2.0 tag to ansible galaxy? 

When using this role, I typically use the releases present on Ansible galaxy, but don't see the [1.2.0](https://github.com/ansible-lockdown/UBUNTU22-CIS/releases/tag/1.2.0) release present yet.

![image](https://github.com/ansible-lockdown/UBUNTU22-CIS/assets/6989713/65543784-bc03-4e43-82fe-38820fbe85cb)

Thanks!

**Comment by colinbruner** [comment]
not super pressing, as I am able to work around by referencing the GH repo in my galaxy.yaml.. but it would still be nice to use ansible-galaxy registry

```diff
-  - name: ansible-lockdown.ubuntu22_cis
+  - src: https://github.com/ansible-lockdown/UBUNTU22-CIS
-    version: V1.1.0
+    version: 1.2.0

```

**Comment by uk-bolly** [comment]
hi @colinbruner 

There has been an upgrade to galaxy over the last couple of week. There has caused a number of irregularities with the how it has worked, we had them all up to date but we are now out of sync completely for no known reason. 
We will be looking at seeing if we can rectify this issues we are seeing as soon as we can.

For reference.
https://forum.ansible.com/tag/galaxy-ng

many thanks

uk-bolly

**Comment by colinbruner** [comment]
awesome, thanks for the update @uk-bolly!

**Comment by uk-bolly** [comment]
hi @colinbruner 

This should be sorted now. I can see 1.3.0 available now and the latest main branch

thanks 

uk-bolly

**Comment by colinbruner** [comment]
Thank you!
