### ISSUE TITLE
Tasks in file  cis_3.5.2.x.yml must be removed

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#16]
**Describe the Issue**

- Tasks for rule 3.5.3.1.1 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.1.2 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.1.3 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.2.1 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.2.2 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.2.3 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.2.4 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.3.1 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.3.2 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.3.3 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    
- Tasks for rule 3.5.3.3.4 appear both in cis_3.5.3.x.yml and cis_3.5.2.x.yml                                                    

The following problems may follow from the problem listed above:

- Rule 3.5.3.2.1 listed with two different titles, namely 'Ensure iptables default deny firewall policy' and 'Ensure iptables loopback traffic is configured'                                                                                                                         
- Rule 3.5.3.2.2 listed with two different titles, namely 'Ensure iptables loopback traffic is configured' and 'Ensure iptables outbound and established connections are configured'                                                                                                     
- Rule 3.5.3.2.3 listed with two different titles, namely 'Ensure iptables outbound and established connections are configured' and 'Ensure iptables default deny firewall policy'                                                                                                       
- Rule 3.5.3.3.1 listed with two different titles, namely 'Ensure ip6tables default deny firewall policy' and 'Ensure ip6tables loopback traffic is configured'                                                                                                                          
- Rule 3.5.3.3.2 listed with two different titles, namely 'Ensure ip6tables loopback traffic is configured' and 'Ensure ip6tables outbound and established connections are configured'                                                                                           
- Rule 3.5.3.3.3 listed with two different titles, namely 'Ensure ip6tables outbound and established connections are configured' and 'Ensure ip6tables default deny firewall policy'   

**Expected Behavior**

The tasks must be deleted from cis_3.5.2.x.yml

**Actual Behavior**

Tasks will be carried out two times.

**Control(s) Affected**
see above

**Environment (please complete the following information):**
n/a

**Additional Notes**
Anything additional goes here

**Possible Solution**
The tasks should be deleted from cis_3.5.2.x.yml

**Comment by MrSteve81** [comment]
Thanks for raising this bug. We will add to a upcoming release to devel.

**Comment by MrSteve81** [comment]
This was added to PR [#22] and is now in devel feel free to test out and let us know.
