### ISSUE TITLE
Update Release Branch

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#163]
## Feature Request or Enhancement

**Summary of Request**
Hi, the `devel` branch is significantly ahead of the release tag. Could a new release tag be cut from the `devel` branch please.

**Describe Alternatives You've Considered**
None

**Comment by uk-bolly** [comment]
hi @zac90 

This should all be fixed now i hope.

many thanks

uk-bolly

**Comment by zac90** [comment]
Yep thanks.
