### ISSUE TITLE
Task for  R2.1.4.4 erroneously tagged and titled as R2.1.4.3 

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#17]
**Describe the Issue**

The task at line

https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/devel/tasks/section_2/cis_2.1.4.x.yml#L66

is actually for rule `2.1.4.4  Ensure ntp is enabled and running`

**Expected Behavior**
Title and tag must match rule 2.1.4.4 rather than 2.1.4.3

**Actual Behavior**
The task is tagged and titled wrongly.

**Control(s) Affected**
2.1.4.3 and 2.1.4.4

**Environment (please complete the following information):**
n/a

**Additional Notes**
Anything additional goes here

**Possible Solution**
use tag/id matching control 2.1.4.4 and title ` Ensure ntp is enabled and running`

**Comment by MrSteve81** [comment]
Thanks for raising this bug. We will add to a upcoming release to devel.

**Comment by MrSteve81** [comment]
This was added to PR [#22] and is now in devel feel free to test out and let us know.
