### ISSUE TITLE
Task 2.1.4.2 has wrong title

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#18]
**Describe the Issue**
The title of task 2.1.4.2 is `Ensure ntp access control is configured` but it should be `Ensure ntp is configured with authorized timeserver`

**Expected Behavior**
The title should match the CIS rule

**Actual Behavior**
The wrong rule text is provided.

**Control(s) Affected**
2.1.4.2

**Environment (please complete the following information):**
n/a

**Additional Notes**
Anything additional goes here

**Possible Solution**
Use the correct CIS rule text as title.

**Comment by MrSteve81** [comment]
Thanks for raising this bug. We will add to a upcoming release to devel.

**Comment by MrSteve81** [comment]
This was added to PR [#22] and is now in devel feel free to test out and let us know.
