### ISSUE TITLE
A value for var: *container_vars_file* is not defined in this role

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/UBUNTU22-CIS#184]
**Question**
In other roles, like RHEL9, I noticed defining:

1. in _defaults/main.yml_ file [a specific value](https://github.com/siemens/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/defaults/main.yml#L5) for **_container_vars_file_ var**
2. in _vars/is_container.yml_ the [actual values](https://github.com/siemens/RHEL9-CIS/blob/devel/vars/is_container.yml) for different variables needed for dealing with a container
3. in _tasks/main.yml_ the [actual handling](https://github.com/siemens/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/tasks/main.yml#L69) of dealing with a container.

In this role(UBUNTU22), I noticed there's only an "is_container: false" statement in [defaults/main.yml](https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/fa365a36ca48f58237d87d5f6d90c380cb7de2ae/defaults/main.yml#L43) file, but:
- the "container_vars_file" var is missing(point 1) above)
- the point above seems fair, as also there's no file in "vars/" dir to be used for dealing with container variables. 

- [ ] - **my concern is related to the fact that _point 3) above seems to be the only one present in Ubuntu22_: there's a task dealing with [container-handling](https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/fa365a36ca48f58237d87d5f6d90c380cb7de2ae/tasks/main.yml#L88), using a reference to `container_vars_file` which is NOT DEFINED in this repository**. 

Is this a small omission or I missed something here for Ubuntu22 role? 

**Environment (please complete the following information):**
N/A

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

Thank you for raising this, you are correct it is an oversight, while we don't actually support containers officially we do try and allow people to work on this. I am adding the required variable and an initial container variable file to an upcoming PR i will be raising.
Any feedback on this would be great.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
I believe that this issue has been addressed and the fix merged?
I will close this issue, please feel free to reopen or raise a new one if this particular problem still exists.

Many thanks

uk-bolly
