### ISSUE TITLE
Several tasks are not carrying the tag corresponding to the rule id

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#19]
**Describe the Issue**
Task for rule 2.3.3 does not carry corresponding tag
Task for rule 4.1.1.3 does not carry corresponding tag
Task for rule 4.2.1.2 does not carry corresponding tag
Task for rule 4.2.1.4 does not carry corresponding tag
Task for rule 6.1.8 does not carry corresponding tag

**Expected Behavior**
A task for CIS rule x.y.z must carry tag of form `rule_x.y.z`

**Actual Behavior**
This is not the case for all tasks

**Control(s) Affected**
See above

**Environment (please complete the following information):**
n/a

**Additional Notes**
Anything additional goes here

**Possible Solution**
Add/correct the tags for the affected tasks.

**Comment by MrSteve81** [comment]
Thanks for raising this bug.  We will add to a upcoming release to devel.

**Comment by MrSteve81** [comment]
This was added to PR [#22] and is now in devel feel free to test out and let us know.
