### ISSUE TITLE
Syntax issue for PRELIM task "List users accounts"

### ISSUE THREAD

**Issue by DianaMariaDDM** [ansible-lockdown/UBUNTU22-CIS#195]
**Describe the Issue**
This task has a when conditional based on rules that do not need this particular prelim task to be executed.

**Expected Behavior**
The when conditional of this task should include only tasks that make use of the register (`ubtu22cis_users`) created by `PRELIM | List users accounts`. As there are no tasks in this role that make use of the said register, there should be no when conditional.

**Actual Behavior**
This task does indeed create a register, but that register is not used for the tasks present in its when conditional ( 6.2.14, 6.2.15, 6.2.16).
These tasks actually make use of another register(`interactive_users_home`) created by `PRELIM | Interactive User accounts`.

**Control(s) Affected**
`PRELIM | List users accounts`
`PRELIM | Interactive User accounts`

**Environment (please complete the following information):**
- branch being used: [e.g. devel]

**Additional Notes**
Anything additional goes here

**Possible Solution**
As a fix, we should remove these tasks from the `PRELIM | List users accounts`  and add them as a when conditional to `PRELIM | Interactive User accounts`. Also, we should add tasks 6.2.11 and 6.2.13 to the when conditional, as they both use the `interactive_users_home` register. This solution will be provided in a PR!

**Comment by uk-bolly** [comment]
I believe that this issue has been addressed and the fix merged?
I will close this issue, please feel free to reopen or raise a new one if this particular problem still exists.

Many thanks

uk-bolly
