### ISSUE TITLE
Inconsistency issue for task 2.2.16

### ISSUE THREAD

**Issue by DianaMariaDDM** [ansible-lockdown/UBUNTU22-CIS#197]
**Describe the Issue**
There appears to be an inconsistency between the when conditionals of the tasks for rule 2.2.16.

**Expected Behavior**
All when conditionals should have the rule's number mentioned. For example: 
  `when:
      - ubtu22cis_rule_2_2_16`

**Actual Behavior**
Only the when conditionals of the tasks within the block contain the rule's number. The when conditional of the actual block does not.

**Control(s) Affected**
`2.2.16 | PATCH | Ensure rsync service is either not installed or masked`

**Environment (please complete the following information):**
- branch being used: [e.g. devel]

**Additional Notes**
Anything additional goes here

**Possible Solution**
I will provide the fix in a PR!

**Comment by uk-bolly** [comment]
I believe that this issue has been addressed and the fix merged?
I will close this issue, please feel free to reopen or raise a new one if this particular problem still exists.

Many thanks

uk-bolly
