### ISSUE TITLE
Task 1.3.1 does not carry corresponding `when` switch

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#20]
**Describe the Issue**
task for rule `1.3.1` should have `when: ubtu22cis_rule_1_3_1` but doesn't

**Expected Behavior**
`when: ubtu22cis_rule_1_3_1` must be present

**Actual Behavior**
`when: ubtu22cis_rule_1_3_1` is not present

**Control(s) Affected**
1.3.1

**Environment (please complete the following information):**
n/a

**Additional Notes**
Anything additional goes here

**Possible Solution**
Enter a suggested fix here

**Comment by MrSteve81** [comment]
Thanks for raising this bug. We will add to a upcoming release to devel.

**Comment by MrSteve81** [comment]
This was added to PR [#22] and is now in devel feel free to test out and let us know.
