### ISSUE TITLE
Small fixes in the documentation of the variables 

### ISSUE THREAD

**Issue by DianaMariaDDM** [ansible-lockdown/UBUNTU22-CIS#201]
## Feature Request or Enhancement
Just some small fixes that enhance the description of the variables from "defaults/main.yml".

**Summary of Request**
Some descriptions need to be added above the variables (e.g. the description of variable `ubtu22cis_aide_init.async/poll`).

Other descriptions need to have the "Controls" keyword near the id of the rules affected (e.g. the description of variable `ubtu22cis_sysctl_kernel_conf`).

And some other descriptions miss the double "#" from their title (e.g. the description of variable `ubtu22cis_passwd_hash_algo` ).

**Describe Alternatives You've Considered**
None.

**Suggested Code**
The suggested code will be provided in a PR.

**Comment by uk-bolly** [comment]
I believe that this issue has been addressed and the fix merged?
I will close this issue, please feel free to reopen or raise a new one if this particular problem still exists.

Many thanks

uk-bolly
