### ISSUE TITLE
ERROR! this task 'ansible.builtin.include_vars' has extra params

### ISSUE THREAD

**Issue by bhavyaNykaa** [ansible-lockdown/UBUNTU22-CIS#209]
Getting the following error when trying to remediate cis benchmarks on an ubuntu22 server -

ERROR! this task 'ansible.builtin.include_vars' has extra params, which is only allowed in the following modules: command, win_shell, script, import_tasks, include, win_command, include_role, include_vars, set_fact, group_by, meta, raw, include_tasks, add_host, shell, import_role

The error appears to be in '/etc/ansible/roles/UBUNTU22-CIS/tasks/main.yml': line 122, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Include audit specific variables
  ^ here

**Environment (please complete the following information):**

- Ansible Version: 2.9.6
- Host Python Version: Python 3.8.10
- Ansible Server Python Version: Python 3.8.10
- Additional Details: I am new to ansible so any help would be really appreciated

**Comment by uk-bolly** [comment]
hi @bhavyaNykaa 

Sorry, but it appears that you are using ansible version 2.9, which we stopped supporting a while ago.
This is currently a minimum of 2.10.1 although i would suggest going to much newer releases e.g. 2.14+
There is a check for the ansible version in the play to ensure that you match the minimal version.

hope that helps.

many thanks

uk-bolly
