### ISSUE TITLE
playbook fails on fresh VM with missing /etc/passwd-

### ISSUE THREAD

**Issue by dlesaffrew** [ansible-lockdown/UBUNTU22-CIS#248]
**Describe the Issue**
A freshly installed VM, based on a template, does not have a backup of the /etc/passwd file (/etc/passwd-).
Rule 6.1.2 fails, stating the the file does not exist (which is correct).

**Expected Behavior**
If the file does not exist, rule 6.1.2 should not stop the playbook.

**Actual Behavior**
The playbook stops with an error message.

**Control(s) Affected**
6.1.2

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.15.12
- Host Python Version: 3.12.3
- Ansible Server Python Version: 3.10.12
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Enter a suggested fix here

**Comment by uk-bolly** [comment]
hi @dlesaffrew 

Thank you again for this issue. The fix has been applied and is now in the main branch and release. I will close this issue, Please reopen if you feel this is not resolved.

Many thanks

uk-bolly
