### ISSUE TITLE
Tasks 2.1.4.4 and 2.3.3 do not have correct when and tag entries, respectively

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#25]
**Describe the Issue**

- The task for rule 2.1.4.4 has entry `ubtu22cis_rule_2_1_4_3` in `when:` part
- The task for rule 2.3.3 has tag `rule_2.2.3` 

**Expected Behavior**
The when/tag entry should be corrected.

**Actual Behavior**
- Setting `ubtu22cis_rule_2_1_4_4: false` in `defaults/main.yml` has no effect
- `-t rule_2.3.3` will not work as expected for rule 2.3.3

**Control(s) Affected**
see above

**Environment (please complete the following information):**
 n/a

**Additional Notes**
n/a

**Possible Solution**
The when/tag entry should be corrected.

**Comment by uk-bolly** [comment]
hi @bgro 

This has been merged into devel. We will be raising the PR to main shortly. If this is working as expected. Please feel free to close this issue.

many thanks

uk-bolly
