### ISSUE TITLE
Specific tags causing issues due to missing vars

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#30]
**Problem**
When using `--tags level1-server`, some tasks in prelim are skipped due to not having the `always` tag attached. This then causes future tasks that are looking for that variable to fail. For example. 

The following task fails: 
`TASK [ubuntu22_cis : "1.1.2.2 | PATCH | Ensure nodev option set on /tmp partition | tmp_systemd"
"1.1.2.3 | PATCH | Ensure noexec option set on /tmp partition | tmp_systemd"
"1.1.2.4 | PATCH | Ensure nosuid option set on /tmp partition | tmp_systemd"] ***
fatal: [molecule-ubuntu2204]: FAILED! => {"msg": "The conditional check 'tmp_mnt_type == 'tmp_systemd'' failed. The error was: error while evaluating conditional (tmp_mnt_type == 'tmp_systemd'): 'tmp_mnt_type' is undefined. 'tmp_mnt_type' is undefined\n\n`

**Environment (please complete the following information):**
The environment is being tested with molecule spinning up a vagrant VM of Ubuntu 22.04
 - Ansible Version: core 2.14.6
 - Host Python Version: 3.10.6
 - Ansible Server Python Version: 3.10.6
 - Additional Details: Molecule Version: 4.0.4

**Possible Solution**
Add the `always` tag to all the tasks in PRELIM if they are there to build facts about the system. When adding the always tag to the PRELIM task `- name: PRELIM | Capture tmp mount type | discover mount tmp type` It worked and continued on and then failed again a few tasks later due to the same issue.

**Comment by uk-bolly** [comment]
hi @zac90 

Thank you for taking the time to raise this issue, I have incorporated the changes in to the Jun23_updates branch. 
If all is working as expected will raise the PR over the next couple of days.

Many thanks again

uk-bolly
