### ISSUE TITLE
Variable and comment issues

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#31]
**Describe the Issue**
I've noticed some of the comments in the `defaults/main.yml` are referncing wrong CIS sections but the right section is referenced in the task playbooks.

`# Section 6 Control Variables`
`# Control 6.1.10`
`# ubtu22cis_no_world_write_adjust will toggle the automated fix to remove world-writable perms from all files`
`# Setting to true will remove all world-writable permissions, and false will leave as-is
ubtu22cis_no_world_write_adjust: true`

Also, one of the variables name is still ubuntu 20 instead of 22.
`# 1.7.1`
`# disable dynamic motd to stop extra sshd message from appearing`
`ubtu20cis_disable_dynamic_motd: true`

The variables below aren't used anywhere. At least not in the devel branch
`ubtu22cis_unowned_owner: root`
`ubtu22cis_no_owner_adjust: true`
`ubtu22cis_ungrouped_group: root`
`ubtu22cis_no_group_adjust: true`
`ubtu22cis_suid_adjust: false`
`ubtu22cis_passwd_label: "{{ (this_item | default(item)).id }}: {{ (this_item | default(item)).dir }}"`

**Expected Behavior**
The variable `ubtu22cis_no_world_write_adjust` is for Section 6.1.9 not 6.1.10

**Possible Solution**
Fix comments
Rename variable to be consistent with others.
Remove variables that are no longer used.

**Comment by uk-bolly** [comment]
hi @zac90 

Thank you for raising the issue and the details feedback. I have updated the controls you have listed and improved the actual tasks that take place to use those controls. I have also updated a few other names to ensure they are as expected.
This will be in the Jun23_updates branch and hope to raise the PR early next week now.

Many thanks

uk-bolly
