### ISSUE TITLE
Tasks 6.2.17 incorrect conditional statement

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#33]
**Describe the Issue**
In Step 6.2.17, the conditional checks if the `length ==0`. This is incorrect as if any "dot files" are found, then the stdout will contain text. This seems to be only for the alert/warning to the user. The actual task that changes the files is correct. 

**Expected Behavior**
This should alert the user when stdout is greater than 0 as it has found dot files.

**Actual Behavior**
Tells the user they have files that are writeable when they don't.

**Possible Solution**
Change `ubtu22cis_6_2_17_audit.stdout | length == 0` to `ubtu22cis_6_2_17_audit.stdout | length > 0`

**Comment by uk-bolly** [comment]
Hi @zac90 

Thank again for picking up the issues, it is with feedback like this we can improve. This has been incorporated to June23_updates branch.
I will raise the PR to dev today for this.

Many thanks

uk-bolly
