### ISSUE TITLE
PRELIM mont type block failing

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#35]
**Describe the Issue**
The `prelim.yml` file has a block that checks the tmp mount type. It registers a variable that is then overwritten if the fstab option is run which causes the next task in the block to fail as it is looking for a value that is no longer in the original variable.

`register: tmp_mnt_type`

This variable is then used in both `when:` to look for "generated" . However, the task changes this variable if it is found. `tmp_mnt_type: fstab`

**Expected Behavior**
The original variable shouldn't be touched and a new variable should be set indicating the mnt type.

**Actual Behavior**
The `tmp_mnt_type` variable changes and loses its original value which causes the third task in the block to fail if the second task succeeded.

**Possible Solution**
Either change the variable name that is used to assign the stdout of the `systemctl is-enabled tmp.mount` command.
Or, add an extra item to the when: to only do the third task if the second task was skipped.

**Comment by uk-bolly** [comment]
Hi @zac90 

Thank you once again for your continued feedback with these issues, its truly helping us to improve things. I have pulled this issue into the July23_issues branch. Which i will leave for a couple of days before requesting merge to devel.

Many thanks once again

uk-bolly
