### ISSUE TITLE
UMASK issues in 5.5.4

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#36]
**Describe the Issue**
umask change in 5.5.4 uses lowercase umask in the `login.defs` file. This causes an incorrect configuration error to appear when trying to login as a user.

**Expected Behavior**
`login.defs` requires capitalised UMASK in the file. See here: https://man7.org/linux/man-pages/man5/login.defs.5.html

**Actual Behavior**
Value isn't being applied and throws an error when trying to login: _configuration error - unknown item 'umask' (notify administrator)_

**Possible Solution**
Create another task that just edits the `login.defs` file as the `/etc/bash.bashrc` and `/etc/profile` require lower case `umask` within the 5.5.4 block.

**Comment by uk-bolly** [comment]
Hi @zac90 

Thank you once again for your continued feedback with these issues, its truly helping us to improve things. I have pulled this issue into the July23_issues branch. Which i will leave for a couple of days before requesting merge to devel.

Many thanks once again

uk-bolly
