### ISSUE TITLE
Issues with 1.1.2.2 fstab option

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#37]
**Describe the Issue**
The section that controls mounting the tmp partition and creating fstab entries results in a failure in mounting. _(Ensure nodev option set on /tmp partition | fstab)_

Also `tmpfs` should not be the forced filesystem as the partition may be using its own filesystem like `ext4`

**Expected Behavior**
The tmp partition should mount without failure at the correct mount point using the correct partition and file system

**Actual Behavior**
It fails to mount because the entry does not have a chosen mount point. The module documentation has been updated and says `name:` is an alias for `path:` 
The current module is: 
 `name: "{{ item.device }}"`
`src: "{{ item.fstype }}"`
`state: present`
`fstype: tmpfs`

**Possible Solution**
Change the task to look something like this:
  `ansible.posix.mount:`
`      path: /tmp`
`      src: "{{ item.device }}"`
`      state: present`
`      fstype: <find out what the partition is otherwise default to tmpfs>`
`      opts: defaults,{% if ubtu22cis_rule_1_1_2_2 %}nodev,{% endif %}{% if ubtu22cis_rule_1_1_2_3 %}noexec,{% endif %}{% if ubtu22cis_rule_1_1_2_4 %}nosuid{% endif %}`

**Comment by uk-bolly** [comment]
Hi @zac90 

Thank you once again for your continued feedback with these issues, its truly helping us to improve things. I have pulled this issue into the July23_issues branch. Which i will leave for a couple of days before requesting merge to devel.

Many thanks once again

uk-bolly

**Comment by Jason-Hendry** [comment]
Not sure if this is related but I'm using Ubuntu autoinstall to partition my disk using LVM. 

After patching the `/etc/fstab` look like this and fails to restart.

```
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/ubuntu-vg/ubuntu-lv during curtin installation
/dev/disk/by-id/dm-uuid-LVM-6JvRcdCzCGbE2n7PpTzZSDZX2YWVg2Ja0f6MtjRu3jyGi8czel4mUIPOXsz8p1gz / ext4 defaults 0 1
# /tmp was on /dev/ubuntu-vg/ubuntu-lv-tmp during curtin installation
/dev/disk/by-id/dm-uuid-LVM-6JvRcdCzCGbE2n7PpTzZSDZX2YWVg2Ja5v4OeXWQlqaLNNeu43hqPouJrD41GgKc /tmp ext4 defaults 0 1
# /var was on /dev/ubuntu-vg/ubuntu-lv-var during curtin installation
/dev/disk/by-id/dm-uuid-LVM-6JvRcdCzCGbE2n7PpTzZSDZX2YWVg2JaWBDyS1kQ3POCKJ1q9eYydp2c0ELIPUz3 /var ext4 defaults 0 1
# /var/tmp was on /dev/ubuntu-vg/ubuntu-lv-var-tmp during curtin installation
/dev/disk/by-id/dm-uuid-LVM-6JvRcdCzCGbE2n7PpTzZSDZX2YWVg2JaJ299bWIKVJG3u9TuT7Tg6JJFA5oeZFkp /var/tmp ext4 defaults 0 1
# /var/log was on /dev/ubuntu-vg/ubuntu-lv-var-log during curtin installation
/dev/disk/by-id/dm-uuid-LVM-6JvRcdCzCGbE2n7PpTzZSDZX2YWVg2Jar53uzB4SwXRkpsaIUsqKFp11kwbj3wzh /var/log ext4 defaults 0 1
# /var/log/audit was on /dev/ubuntu-vg/ubuntu-lv-var-log-audit during curtin installation
/dev/disk/by-id/dm-uuid-LVM-6JvRcdCzCGbE2n7PpTzZSDZX2YWVg2JaL1vv2bDHq2wmubX1rdVDqfd7ygpHfjqZ /var/log/audit ext4 defaults 0 1
# /home was on /dev/ubuntu-vg/ubuntu-lv-home during curtin installation
/dev/disk/by-id/dm-uuid-LVM-6JvRcdCzCGbE2n7PpTzZSDZX2YWVg2JayqEEAnMwmXbamhIKxM46wUU9UO0M0vra /home ext4 defaults 0 1
# /boot was on /dev/sda2 during curtin installation
/dev/disk/by-uuid/1834daca-ccc4-4328-9b44-f0d07ef9fdf2 /boot ext4 defaults 0 1
# /boot/efi was on /dev/sda1 during curtin installation
/dev/disk/by-uuid/D83E-0378 /boot/efi vfat defaults 0 1
/swap.img       none    swap    sw      0       0
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
vagrant /vagrant vboxsf uid=1000,gid=1000,_netdev 0 0
#VAGRANT-END
ext4 /dev/mapper/ubuntu--vg-ubuntu--lv--tmp tmpfs defaults,nodev,noexec,nosuid 0 0
ext4 /dev/mapper/ubuntu--vg-ubuntu--lv--var xfs defaults,nodev,nosuid 0 0
ext4 /dev/mapper/ubuntu--vg-ubuntu--lv--var--tmp xfs defaults,noexec,nosuid,nodev 0 0
ext4 /dev/mapper/ubuntu--vg-ubuntu--lv--var--log xfs defaults,nodev,noexec,nosuid 0 0
ext4 /dev/mapper/ubuntu--vg-ubuntu--lv--var--log--audit xfs defaults,noexec,nodev,nosuid 0 0
ext4 /dev/mapper/ubuntu--vg-ubuntu--lv--home xfs defaults,nodev,nosuid, 0 0
/dev/shm /dev/shm tmpfs defaults,nodev,nosuid,noexec 0 0
```
