### ISSUE TITLE
undefined var when running with certain rules.

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#39]
**Describe the Issue**
The variable `tmp_mnt_type` needs to be set for 1.1.2.2/3/4 to run. This isn't set if the PRELIM role is skipped due to the `when:` conditions not being met. 
If the following vars are set to `false` it results in the PRELIM task not running and then causing the task for 1.1.2.2 to fail to run because the when: statement for that task relies on `tmp_mnt_type` being defined.
`ubtu22cis_rule_1_1_2_1 or`
`ubtu22cis_rule_1_1_2_2 or`
`ubtu22cis_rule_1_1_2_3 or`
`ubtu22cis_rule_1_1_2_4`

**Expected Behavior**
The playbook should work even if the variable isn't defined.

**Actual Behavior**
The playbook fails cause the var isn't defined when the PRELIM is skipped due to those rule vars being all false.

**Possible Solution**
Three possible fixes from highest to lowest recommendation:
 - Define a default value for the `tmp_mnt_type`
 - Add another condition to be `tmp_mnt_type is defined`
 - Move it to the bottom of the `when:` list so that is will only be assessed if the other criteria are met first.

**Comment by uk-bolly** [comment]
Hi @zac90 

Thank you once again for your continued feedback with these issues, its truly helping us to improve things. I have pulled this issue into the July23_issues branch. Which i will leave for a couple of days before requesting merge to devel.

Many thanks once again

uk-bolly
