### ISSUE TITLE
cis_5.4.x.yml logic idempotency issues

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#40]
**Describe the Issue**
There seems to be some overwriting logic where it is set and then removed in a task later. I found this when trying to test idempotency of the whole playbook. There looks to be multiple issues with the 5.4.x section that modifies pam files. One is that some tasks are using `lineinfile` like `5.4.3` and others are using the `pamd` module like `5.4.4`. Also in the `5.4.4` task, the ternary sets it to either `args_present` or `absent`. `absent` removes the whole line, I think this should be `args_absent` as per the module documentation.

**Expected Behavior**
The tasks should not be overwriting eachother and thus causing idempotency issues.

**Actual Behavior**
One task sets a value and another future task removes that value.

**Control(s) Affected**
5.4.x

**Possible Solution**
Use the `pamd` module for all the tasks that modify pam files and also correctly specify the state value.

**Comment by uk-bolly** [comment]
Hi @zac90 

Thank you once again for your continued feedback with these issues, its truly helping us to improve things. I have pulled this issue into the July23_issues branch. Which i will leave for a couple of days before requesting merge to devel.

Many thanks once again

uk-bolly
