### ISSUE TITLE
cis_1.5.x duplication

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#41]
**Describe the Issue**
Two tasks are used for 1.5.1 both performing the same job but using different methods. 

**Expected Behavior**
Only one task should be managing this, preferably with the sysctl module to avoid idempotency issues.

**Actual Behavior**
Idempotency issues occur due to both tasks performing the same job with a different method.

**Control(s) Affected**
1.5.1

**Possible Solution**
Use one task, preferably the `sysctl module` one. Also make that sysctl more like the other controls that modify `sysctl.conf`

**Comment by uk-bolly** [comment]
Hi @zac90 

Thank you once again for your continued feedback with these issues, its truly helping us to improve things. I have pulled this issue into the July23_issues branch. Which i will leave for a couple of days before requesting merge to devel.

Many thanks once again

uk-bolly
