### ISSUE TITLE
Audit tasks don't have tag: always

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#42]
**Describe the Issue**
The audit tasks that are listed in the `main.yml` file don't have the `always` tag to them. This causes them not to run when using a specific tag like `level1-server`. 

**Expected Behavior**
Audit tasks should run even if calling playbook with tags.

**Actual Behavior**
The audit playbook doesn't run.

**Possible Solution**
Add the `- always` tag to the associated tasks in `main.yml`.  They are still manually controlled by a variable, so it is okay for them to have the `always` attached.

**Comment by uk-bolly** [comment]
Hi @zac90 

Thank you once again for your continued feedback with these issues, its truly helping us to improve things. I have pulled this issue into the July23_issues branch. Which i will leave for a couple of days before requesting merge to devel.

Many thanks once again

uk-bolly
