### ISSUE TITLE
pre_remediation_audit.yml incorrect permissions on files

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#44]
**Describe the Issue**
In the playbook `pre_remediation_audit.yml` The task "_- name: Pre Audit Setup | copy to audit content files to server_" copies files over from the control node to the host however sets the permissions as `644`. This causes the `run_audit.sh` script to get a permission denied error because it doesn't have the execute bit set.

**Expected Behavior**
The shell script should execute normally, no matter the way the files are transferred to the target machine.

**Actual Behavior**
The shell script cannot execute because it doesn't have the execute bit set.

**Possible Solution**
Create a new task to ensure executable is set on the `run_audit.sh` file before it is called. This will ensure robustness for however method is used to copy the audit config over.

**Comment by uk-bolly** [comment]
hi @zac90 

Thank you for raising this issue, i have changed the mode to preserve to copy the files overs and preserver the permissions as you have set from the original location. That should resolve this issue.
It is currently in the Jul23_updates branch which i hope to get released soon.

Many thanks

uk-bolly
