### ISSUE TITLE
pre_remediation_audit.yml always tag for vars file copy.

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#45]
**Describe the Issue**
The following task requires the `always` tag so that the goss vars file that relates to the ansible environment can be copied over.
`- name: Pre Audit Setup | Copy ansible default vars values to test audit`

**Expected Behavior**
This task should run when trying to audit.

**Actual Behavior**
The task does not run if another tag is specified.

**Possible Solution**
Add the always tag to the task.

**Comment by uk-bolly** [comment]
hi @zac90 

Thank you for raising this issue, great improvement i have incorporated to July23_updates branch which i hope to get merged soon.

Many thanks

uk-bolly
