### ISSUE TITLE
Issue in section "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set faillock common-auth"

### ISSUE THREAD

**Issue by big-yellow-duck** [ansible-lockdown/UBUNTU22-CIS#52]
**Describe the Issue**
This part will lock me out of the device and it fails halfway with the error " incorrect sudo password"

**Expected Behavior**
It should properly modify the /etc/pam.d/common-auth file without breaking authentication

**Actual Behavior**
It breaks the authentication because it fails to add the line with authsucc needed to pass authentication

**Control(s) Affected**
Authentication

**Environment (please complete the following information):**
 - Ansible Version: 2.13.11
 - Host Python Version: 3.8.2
 - Ansible Server Python Version: Python 3.10.6
 - Additional Details: I'm running on raspberry pi 4 ubuntu server 22.04

**Possible Solution**
I have modified the play in this section to temporarily comment out the pam_deny.so line to all changes can go through then enabling it back.

Here is the modification:

- name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | temporarily disable pam_deny.so"
    ansible.builtin.replace:
      path: /etc/pam.d/common-auth
      regexp: '^auth\s+requisite\s+pam_deny.so'
      replace: '#auth    requisite                        pam_deny.so'

  - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set faillock common-auth"
    ansible.builtin.lineinfile:
        path: /etc/pam.d/common-auth
        regexp: '^{{ item.regexp }}'
        line: "{{ item.line }}"
        insertbefore: "{{ item.before | default(omit) }}"
        insertafter: "{{ item.after | default(omit) }}"
    loop:
        - { regexp: 'auth\s+required\s+pam_faillock.so', line: 'auth    required            pam_faillock.so preauth', before: '^.*pam_unix.so'}
        - { regexp: 'auth\s+sufficient\s+pam_faillock.so', line: 'auth    sufficient          pam_faillock.so authsucc', before: '^.*pam_deny.so'}
        - { regexp: 'auth\s+[default=die]\s+pam_faillock.so', line: 'auth    [default=die]       pam_faillock.so authfail', after: '^.*pam_unix.so'}
        
  - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | enable pam_deny.so"
    ansible.builtin.replace:
      path: /etc/pam.d/common-auth
      regexp: '^#auth\s+requisite\s+pam_deny.so'
      replace: 'auth    requisite                       pam_deny.so'

**Comment by uk-bolly** [comment]
hi @big-yellow-duck 

Thank you for raising this issue and providing a solution. I have been investigating this already and i am unable to reproduce the issue (noting it is a clean build used for testing). It maybe something that others have that i am not aware of.

i have tried a couple of ways and wonder if we changed the routine it would work for you.

Original
```
TASK [UBUNTU22-CIS : 5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set faillock common-auth] ***
changed: [ubuntu22_04] => (item={'regexp': 'auth\\s+required\\s+pam_faillock.so', 'line': 'auth    required            pam_faillock.so preauth', 'before': '^.*pam_unix.so'})
changed: [ubuntu22_04] => (item={'regexp': 'auth\\s+[default=die]\\s+pam_faillock.so', 'line': 'auth    [default=die]       pam_faillock.so authfail', 'after': '^.*pam_unix.so'})
changed: [ubuntu22_04] => (item={'regexp': 'auth\\s+sufficient\\s+pam_faillock.so', 'line': 'auth    sufficient          pam_faillock.so authsucc', 'after': '^.*authfail'})
```
i have rebuilt in between testing

Proposed
```
changed: [ubuntu22_04] => (item={'regexp': 'auth\\s+required\\s+pam_faillock.so', 'line': 'auth    required            pam_faillock.so preauth', 'before': '^.*pam_unix.so'})
changed: [ubuntu22_04] => (item={'regexp': 'auth\\s+sufficient\\s+pam_faillock.so', 'line': 'auth    sufficient          pam_faillock.so authsucc', 'after': '^.*pam_unix.so'})
changed: [ubuntu22_04] => (item={'regexp': 'auth\\s+[default=die]\\s+pam_faillock.so', 'line': 'auth    [default=die]       pam_faillock.so authfail', 'before': '^.*authsucc'})
```

The proposed just changing the logic and syntax of the order e.g.
```
loop:
            - { regexp: 'auth\s+required\s+pam_faillock.so', line: 'auth    required            pam_faillock.so preauth', before: '^.*pam_unix.so'}
            - { regexp: 'auth\s+sufficient\s+pam_faillock.so', line: 'auth    sufficient          pam_faillock.so authsucc', after: '^.*pam_unix.so'}
            - { regexp: 'auth\s+[default=die]\s+pam_faillock.so', line: 'auth    [default=die]       pam_faillock.so authfail', before: '^.*authsucc'}
```

If i could possibly ask if the proposed implementation is an improvement for you and your configuration.

many thanks

uk-bolly

**Comment by big-yellow-duck** [comment]
I have verified it by running the updated playbook to modify the file in a docker container with user auth set up.

Thank you for help! @uk-bolly
