### ISSUE TITLE
There is no /etc/systemd/timesyncd.conf.d folder by default - Step 2.1.3.1

### ISSUE THREAD

**Issue by arvatoth-vcc** [ansible-lockdown/UBUNTU22-CIS#62]
**Describe the Issue**
In step 2.1.3.1. copying 50-timesync.conf file to the  /etc/systemd/timesyncd.conf.d folder, but this is not exists by default.

**Expected Behavior**
Need to create folder in a previous task.

**Actual Behavior**
Error happens, no such directory.

**Environment:**

- branch being used: devel
- Ansible Version: 2.12.0
- Host Python Version: 3.10.12
- Ansible Server Python Version: 3.10.12
- Additional Details: Ubuntu 22.04 in KVM virtual server

**Possible Solution**
Create folder before copying task.

**Comment by uk-bolly** [comment]
hi @arvatoth-vcc 

Thank you for raising this issue. The fix has now been added to the devel branch.
Please let us know if you are still seeing the issue?

Many thanks

Mark

**Comment by arvatoth-vcc** [comment]
hi @uk-bolly,

Great, thank you, working perfectly.
