### ISSUE TITLE
Ubuntu22-CIS can't logon after remediation

### ISSUE THREAD

**Issue by Acenl12** [ansible-lockdown/UBUNTU22-CIS#65]
**Question**
I can;t logon anymore after I applied the UBUNTU22-CIS on an Ubuntu 22.04 running in Hyper-V. I'm trying to logon using the console.
I'm getting the error, `sorry password authentication didn't work.`

**Comment by uk-bolly** [comment]
Hi @Acenl12 

Thank you for raising the this issue and interaction on the discord community. I feel the biggest change we could make would be to make the default for the following settings
```sh 
ubtu22cis_disruption_high: false
```

I will raise this work to take place in the next PR

Many thanks

uk-bolly

**Comment by jamesv1994** [comment]
I ran into the same issue. A solution for us (as we want to use a central directory service which takes care of this) was to deactivate Ruleset 5.4.2 
`ubtu22cis_rule_5_4_2: false`


I was unable to dig further but could identify this as the source of disruption. 

Hope this helps.

**Comment by Acenl12** [comment]
Running it on ubuntu-server instead ubuntu-desktop then it worked fine. Thanks for the help so far.
