### ISSUE TITLE
How to disable "Grub User root has no password" checks?

### ISSUE THREAD

**Issue by ps-spb** [ansible-lockdown/UBUNTU22-CIS#67]
**Describe the Issue**

I'm targeting an environment where we cannot enforce this control, and want to disable this setting.

Setting the following variables will toggle the checks for these related settings:
```
ubtu22cis_rule_1_4_1: false # changed spb - secure boot
ubtu22cis_rule_1_4_2: false # changed spb - secure boot
ubtu22cis_rule_1_4_3: false # changed spb - secure boot
```

However, the block will fall through to this area:
https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/2a7c6499a146ab648f97380f681b4faac5f070c5/tasks/main.yml#L65

which leads to this code block:
https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/2a7c6499a146ab648f97380f681b4faac5f070c5/tasks/main.yml#L81

causing a failure.
 
**Expected Behavior**
The code block isn't execute if the rules ubtu22cis_rule_1_4_* are set to false.

**Actual Behavior**

```
TASK [UBUNTU22-CIS : Check ubtu22cis_grub_user password variable has been changed | if password blank or incorrect type and not being set] ***
task path: /root/.ansible/pull/U-2I0Y50GO301BQ.portswigger.internal/roles/UBUNTU22-CIS/tasks/main.yml:81
fatal: [localhost]: FAILED! => {
    "assertion": "( ubtu22cis_password_set_grub_user.stdout | length > 10 ) and '$y$' in ubtu22cis_password_set_grub_user.stdout",
    "changed": false,
    "evaluated_to": false,
    "msg": "Grub User root has no password set or incorrect encryption"
}
```
**Control(s) Affected**
1.4.x

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: ansible 2.10.8
- Host Python Version: 3.10.12
- Ansible Server Python Version: 3.10.12 (same - being run locally)
- Additional Details:

We are targetting AWS WorkSpaces Ubuntu offering.

**Comment by uk-bolly** [comment]
hi @ps-spb 

Thank you for taking the time to raise issue https://github.com/ansible-lockdown/UBUNTU22-CIS/issues/67. A fix has been added and merged into the devel branch.
This give you the conditional to enable you to skip the test by setting the follow to false.
```
ubtu22cis_set_grub_user_pass
```
I hope that this works as expected?

Many thanks once again

uk-bolly

**Comment by ps-spb** [comment]
Hi - yep thanks this works perfectly :-)
