### ISSUE TITLE
Discovering Interactive Users 

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/UBUNTU22-CIS#86]
**Describe the Issue**
Rules in section 6.2. are using the variable called `interactive_users_home`, which is registered in `PRELIM | Interactive User accounts` task:
```
- name: "PRELIM | Interactive User accounts"
  ansible.builtin.shell: 'cat /etc/passwd | grep -Ev "nologin|/sbin|/bin" | cut -d: -f6'
  register: interactive_users_home
  ... 
```
I discovered that the mechanism used for identifying such users is not working well, as the values used for `grep` prevent really identifying such users.

**Expected Behavior**
The `ansible.builtin.shell` command should identify all interactive users.

**Actual Behavior**
Interactive users are not returned by the above command.
```
# No filtering at all
example@exampleHost:~$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
[...]
example:x:1000:1000:,,,:/home/example:/bin/bash
_rpc:x:108:65534::/run/rpcbind:/usr/sbin/nologin
statd:x:109:65534::/var/lib/nfs:/usr/sbin/nologin


# Filtering for 'nologin' indeed gets out most of the users, respectively some of the non-interactive ones
example@exampleHost:~$ cat /etc/passwd | grep -Ev "nologin"
root:x:0:0:root:/root:/bin/bash
sync:x:4:65534:sync:/bin:/bin/sync
example:x:1000:1000:,,,:/home/example:/bin/bash

# Adding '/bin' in this manner, as a filter for the reverse grep, will end up filtering also interactive users(e.g. ones which have /bin/bash or /bin/sh as their login-shell)
example@exampleHost:~$ cat /etc/passwd | grep -Ev "nologin|/bin"                                     ****** Here's the issue, in my opinion
example@exampleHost:~$

# Our suggestion, for filtering some values like `/bin/false` only on the relevant fields:
example@exampleHost:~$ grep -E -v '^(root|halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "'"$(which nologin)"'" && $7 != "/bin/false") { print $6 }'
/home/example
```

**Control(s) Affected**
6.2.* (e.g. 6.2.11, 6.2.13, etc.)

**Environment (please complete the following information):**

- branch being used: [e.g. devel]

**Additional Notes**
- _The root, sync, shutdown, and halt users are [exempted](https://www.tenable.com/audits/items/CIS_CentOS_7_v3.1.2_Server_L1.audit:6fb344ee81855c8fbdafa204a7cd25c6) from requiring a non-login shell._

**Possible Solution**
I'll provide a PR immediately.

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This issue was merged to devel a couple of weeks ago.
I will close this Issue, if this does not resolve your issue please reopen.

Many thanks as always

uk-bolly
