### ISSUE TITLE
ubtu22cis_passwd value

### ISSUE THREAD

**Issue by gshockxia** [ansible-lockdown/UBUNTU22-CIS#9]
**Question**
what ubtu22cis_passwd value?

**Environment :**
 - Ansible Version: [2.9.27] 
 - Host Python Version: [3.10.6]
 - Ansible Server Python Version: [2.7.5]
 - Additional Details: tasks/section_5/cis_5.5.x.yml

I can't find the ubtu22cis_passwd value in defaults/main.yml,and CIS 5.5.1.2 run failed.
Could you tell me the value of ubtu22cis_passwd  where to set ?

**Comment by uk-bolly** [comment]
Hi @gshockxia 

Thank you for the question. The value is set when the task runs the parse_etc_password portion of the playbook.
Are you running the playbook in it entirety ? Or are you running other options?

I am just working on the official cis_v1.0.0 at this moment with an almost complete branch (cis_release branch) ready to be tested (it doesn't have audit yet).
This release should be in devel in the next week so long as feedback and testing works as expected.

regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @gshockxia 

The official release is now in devel. If you could let me know if you still see any issues. I believe this is now ironed out.

Many thanks 

uk-bolly

**Comment by gshockxia** [comment]
Hi @uk-bolly 

Thanks for your reply.

I am running the playbook partly on CentOS7.9.

TASK [/root/UBUNTU22-CIS-devel : 5.5.1.2 | PATCH | Ensure password expiration is 365 days or less | Set existing users PASS_MAX_DAYS] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no test named '>='
fatal: [192.168.1.33]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

![image](https://user-images.githubusercontent.com/3355242/231190720-84b0684a-2f35-4073-bb6f-dec57ffc4f29.png)
I search on google,may be Jinja2 module version issue.

Running the playbook local is ok.
![image](https://user-images.githubusercontent.com/3355242/231191758-7502591a-fd04-42f0-95f2-3728661dbff0.png)

**Comment by uk-bolly** [comment]
hi @gshockxia 

Thank you for the feedback.
You have actually highlighted an issue the ansible version check was not updated across the board. I have a new PR open to resolve this and linked to this issue.
This does carry a minimum of ansible 2.10.1 you are correct jinja2 would be causing your issue when running on python 2.7. Seeing the actual error output highlighted it straightaway. 

Hope to have that merged today into devel

Many thanks

uk-bolly

**Comment by edb-shaunb** [comment]
I am using the ubuntu user to run the ansible role, once you have run the role, it sets a password for this user I think. If you set one that you know, the playbook exits with: 

fatal: [54.92.207.98]: FAILED! => {"msg": "Missing sudo password"}

So the ubuntu user can't sudo to run the playbook. I'm confused as to whether or where you need to specify this? 
Thanks

**Comment by uk-bolly** [comment]
hi @edb-shaunb 

Its doesn't set the password in this case it is saying that you have control enabled that will require a password to be set for the account. Several changes are made to sudoers including removing the NOPASSWD option. This can then have a knock on effect to other pam controls. So it fails stating that you dont have a password for the account.

I hope that helps

uk-bolly
