### ISSUE TITLE
Controls 5.5.1.1, 5.5.1.2, 5.5.1.3, and 5.5.1.4 are not executed for the root user, even though they should.

### ISSUE THREAD

**Issue by bgro** [ansible-lockdown/UBUNTU22-CIS#96]
**Describe the Issue**
Controls 5.5.1.1, 5.5.1.2, 5.5.1.3, and 5.5.1.4 are not executed for the root user, even though they should,
because the respective `chage` operations are restricted to UIDs of 1000 and above.

**Expected Behavior**
For these controls, `chage` should be executed for all users.

**Actual Behavior**
see above

**Control(s) Affected**
5.5.1.1, 5.5.1.2, 5.5.1.3, and 5.5.1.4

**Environment (please complete the following information):**

- branch being used: devel

**Additional Notes**
Anything additional goes here

**Possible Solution**
I will create a pull request.

**Comment by uk-bolly** [comment]
hi @bgro 

This issue was merged to devel a couple of weeks ago.
I will close this Issue, if this does not resolve your issue please reopen.

Many thanks as always

uk-bolly
